# Plugin recompiled and cracked by NaulbiMIX | Sponsored by FlatiCommunity (https://t.me/flaticommunity)
# Specially publication for https://teletype.in/@naulbimix/rumine
#
# Плагин разработан командой кодеров UniversalStudio.
# Если Вы обнаружите какой-либо баг, незамедлительно сообщите нам.
# Vk: vk.com/universalstudio
# Site: u-studio.su

name: UniversalStreams
main: ru.universalstudio.streams.Manager

author: UniversalStudio Inc
version: 1.0

softdepend: [Vault]

commands:
 streams:
 stream: